// <auto-generated />
using System;
using AJWManagementPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AJWManagementPortal.Data;

namespace MTJ_Product.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210407120950_DBV1")]
    partial class DBV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AJWManagementPortal.Models.BankBalane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankBalance")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("closingBankBalance")
                        .HasColumnType("int");

                    b.Property<int>("deposit")
                        .HasColumnType("int");

                    b.Property<int>("tax")
                        .HasColumnType("int");

                    b.Property<int>("transaction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("bankBalane");
                });

            modelBuilder.Entity("AJWManagementPortal.Models.MeezanBankIEReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.Property<string>("CDO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Cradit")
                        .HasColumnType("real");

                    b.Property<float>("Debit")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgceo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imgdgm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imggm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MeezanBankIEReports");
                });

            modelBuilder.Entity("AJWManagementPortal.Models.MeezanBankIEVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("checkNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("purpose")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MeezanBankIEVouchers");
                });

            modelBuilder.Entity("AJWManagementPortal.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("AJWManagementPortal.Models.aDailyCash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("accountant")
                        .HasColumnType("real");

                    b.Property<float>("clearedAmount")
                        .HasColumnType("real");

                    b.Property<float>("income")
                        .HasColumnType("real");

                    b.Property<float>("lnClearedAmount")
                        .HasColumnType("real");

                    b.Property<float>("online")
                        .HasColumnType("real");

                    b.Property<float>("pOrder")
                        .HasColumnType("real");

                    b.Property<float>("paidAmount")
                        .HasColumnType("real");

                    b.Property<string>("purchaser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("remainingGained")
                        .HasColumnType("real");

                    b.Property<float>("surplus")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("aDailyCashes");
                });
#pragma warning restore 612, 618
        }
    }
}
